### ISSUE TITLE
copyRecursivelySync` is deprecated

### ISSUE THREAD

**Issue by sandstrom** [quandl/grunt-broccoli#19]
I just wanted to let you know that `copyRecursivelySync` is deprecated.

Example of the change needed, from another repo:
https://github.com/tildeio/htmlbars/pull/76/files

REFERENCE
https://github.com/broccolijs/broccoli-kitchen-sink-helpers/blob/f5b68e7ee73480b2ce6587d62e7f4f0c455561e5/index.js#L132

**Comment by Dremora** [comment]
With #28 merged, this can be closed now.
