### ISSUE TITLE
Error: Invalid tree found. You must supply a path or an object with a `read` function.

### ISSUE THREAD

**Issue by andre-meier** [quandl/grunt-broccoli#30]
I am experiencing a problem using grunt-broccoli. When I manually run "broccoli build", everything works fine. Using grunt-broccoli i get the error 

```
Error: Invalid tree found. You must supply a path or an object with a `read` function.
```

I tracked this error down to lib/plugin.js, where it happens, when the Brocfile is included via require in combination with 'broccoli-babel-transpiler':

```
tree = require(configPath);
```

When I drop 'broccoli-babel-transpiler' from my Brocfile.js everything works just fine. When I manually require the Brocfile in the Gruntfile.js without using it, everything is working as expected, even with 'broccoli-babel-transpiler' wired up.

**Comment by andre-meier** [comment]
As newer versions of the broccoli-babel-transpiler plugin wont work with my workarounds, I dived a bit deeper into the problem and found that updating broccoli in grunt-broccoli fixes my problems. I created a pull-request with the updates package.json.

**Comment by jbyck** [comment]
@andre-meier Sorry, this project isn't supported by Quandl anymore.  We don't control the npm package.  I will close this issue and update the README.
